# Basic
title: Effun
subtitle: effunwayj@njust.edu.cn
description: Hi! Welcome to my blog
# å¤´åƒé‡Œé¢çš„æ ‡é¢˜
avatarTitle: å½­ä¸€å‡¡
# å¤´åƒé‡Œé¢çš„æè¿°
avatarDesc:   SLAM  /  ç§»åŠ¨æœºå™¨äºº  /  æ§åˆ¶ç®—æ³•
url: "https://effun.xyz"

# åšå®¢æ˜¯å¦è‡ªåŠ¨ç”Ÿæˆç›®å½•ï¼Œfalseä¸ºä¸ç”Ÿæˆ
enableToc: true

# Comment
#comment:
    # livere: MTAyMC81MDk5NC8yNzQ3Ng  # https://www.livere.com
    # disqus: effun
    # uyan: 2143225  # æœ‰è¨€id,ç™»å½•æœ‰è¨€å®˜ç½‘ç”³è¯·

# Social
#social:
    #weibo: 5366874726 
    # github: Effun_141
    # zhihu: panpanleopard
    # juejin: xxx
    #jianshu: 2ada30d8d0f7
    # twitter: 
    # mail: effunwayj@njust.edu.cn


# ç™¾åº¦ç»Ÿè®¡ 
# ä½¿ç”¨åšå®¢æ¨¡æ¿è¯·å»æ‰æˆ–è€…æ›´æ¢ id 
# baidu:
#     id: 8ba1c6be0953b6f9c2ba38e57f615421  

# Google Analytics
# ä½¿ç”¨åšå®¢æ¨¡æ¿è¯·å»æ‰æˆ–è€…æ›´æ¢ id
# ga:
#     id: UA-84134159-3  
#     host: auto  


# ã€Š----------------- ä¸Šé¢çš„ä¿¡æ¯ä¿®æ”¹æˆä½ è‡ªå·±çš„ ---------------------------ã€‹
#
#
#  _post/ ä¸‹çš„æ–‡ç« æ›´æ¢æˆä½ è‡ªå·±çš„æ–‡ç« 
#  å¸®å¿™starä¸€ä¸‹ï¼Œæ„Ÿè°¢~ğŸ˜† åœ°å€ï¼š https://github.com/leopardpan/leopardpan.github.io
#
#
# ã€Š--------------- ä¸‹é¢çš„ä¿¡æ¯å¯ä»¥è‡ªè¡Œé€‰æ‹©æ˜¯å¦ä¿®æ”¹ ------------------------ã€‹


permalink: /:year/:month/:title/
# Format
highlighter: rouge

textColor: #FF0000

# supported colors: blue, green, purple, red, orange or slate. If you need clear, leave it empty.
cover_color: clear

# The blog button should not be removed.
blog_button:
   # title: åšå®¢ä¸»é¡µ
     title: Blog Homepage

# Navigation buttons in the front page.s
nav:
    # - {title: æ‰€æœ‰æ–‡ç« , description: archive, url: '/archive'}   
    # - {title: æ ‡ç­¾åˆ†ç±», description: tags, url: '/tags'}      
 #   - {title: æŠ€æœ¯æ”¯æŒ, description: support, url: '/support'}      
    # - {title: ä¸ªäººç®€å†, description: about, url: '/about'}   
     - {title: Tags, description: tags, url: '/tags'}     
     - {title: Articles, description: archive, url: '/archive'}   
 #    - {title: æŠ€æœ¯æ”¯æŒ, description: support, url: '/support'}      
     - {title: About Me, description: about, url: '/about'}  
    
    

# Pagination
gems: [jekyll-paginate,jekyll-sitemap]
paginate: 20
paginate_path: "page/:num/"


